### ISSUE TITLE
Communication is lacking

### ISSUE THREAD

**Issue by corecode** [HackEPFL/suggestions#7]
HackEPFL is communicating poorly and does not give the impression of an inclusive/plastic structure.

Suggestions to resolve:

a) use mailing lists to facilitate online communication
b) have informal meet-ups in for offline communication
c) publish ideas and decisions publicly
d) show inclusiveness by explicitly stating that HackEPFL is formed and progressed by everybody interested, not only by currently active people

I can offer hosting for (a), and occasional guidance of meetings for (b).

**Comment by FredericJacobs** [comment]
Hi,

First of all, thanks for your feedback.

Really glad you show interest in Hackers at EPFL. During the past few weeks we've been mainly dealing with bureaucracy inside EPFL. We've been looking to comply as much as possible with the Terms & Conditions of being an EPFL association. There has been a lot of personal documentation going on. 

In addition to this, we've been talking to other people from the associative world, from PolyProg to Martin Vetterli. Talking to them has been really instructive in decrypting the scope of activities we can achieve on the campus. 

One of the biggest reasons why there is a lack of communication is because the Association itself [isn't completely settled yet](https://github.com/HackEPFL/suggestions/issues/4). 

As soon as the association will be recognized, then we'll be able to find a common ground in terms of openness inside the association. 

There will be people in charge because in the end of the day someone has to take initiatives and take the lead. HackEPFL will have sponsors to cover basic expenses and there will be people who will be assigned a position to deal with sponsors and more administrative stuff.

Regarding communication, GitHub issues are doing a good job to complete our current needs right now.

Feel free to add things you want to see in Hackers @ EPFL because our final decisions are made on GitHub issues.

We will probably do meet ups at Sat soon enough. 

And regarding hosting, I'm co-founded a hosting company so we should be fine there. Thanks for the offer ;)

**Comment by corecode** [comment]
This sounds like "thanks but no thanks, not interested in anything you're saying".  Well, then HackEPFL will likely be as successful as other EPFL associations.

**Comment by romac** [comment]
I'm sorry you feel that way, because we're definitely interested in what you're saying, otherwise we wouldn't be replying promptly, and at length. On the other hand, we have our own vision that we want to pursue at the very beginning, and we feel like it would be very hard if we start to focus on too many things since day 0: it's better if we start very small, and then let people shape "Hackers at EPFL" in whichever way they want. As we said, the first step is to become a recognized association in EPFL—everything else will come right after.

Regarding the other associations in EPFL, we'd love to become as successful as they are. Most of them have been around for years, with tens of active members, and many events that contributed to the EPFL scene. We're kickstarting a new association not because we consider ourselves better than them, but just because we want to fill the few gaps not covered by the others! That's why we're already in the talks for collaborations.

**Comment by corecode** [comment]
The problem is that whenever (rarely) something is communicated, I never feel like I (or others) could be part of the group, and shape its journey.

For example, take your first sentence: "we're definitely interested in what you're saying".  To me, this creates a grouping: "we" (HackEPFL) vs "you" (not HackEPFL).  Why am I not part of HackEPFL?  I don't get the impression that I can be.

**Comment by rorist** [comment]
I think we should do an open meeting with interested ppl, I know you've already done it, but it was not announced anywhere afaik. Something like a kickoff drinking event (nothing related to administrative stuff like creating the association) , what about that ?

**Comment by FredericJacobs** [comment]
Sure. I'm going back to my hometown for the holidays so I won't be back in Lausanne before mid-January.
Would love to be there.

**Comment by FredericJacobs** [comment]
Closed for now, feel free to reopen.

**Comment by corecode** [comment]
Still no communication happening, except for this issue being closed.
